(()=>{
  const offer=document.getElementById("preorderOffer"),policy=window.AURACoastGo;
  if(!offer||!policy)return;
  const storageKey="aura-home-free-shipping-coastgo-yoga-20261008";
  const promotion={promotion_id:policy.shippingPromotionId,promotion_name:"CoastGo & Yoga Cruiser — free shipping",creative_slot:"homepage_modal",coupon:policy.shippingCode,currency:"AUD",items:[...policy.skus.map(item_id=>({item_id,item_name:"AURA PADDLE CoastGo",price:299,quantity:1})),{item_id:"AP734955",item_name:"AURA PADDLE Yoga Cruiser",price:749,quantity:1}]};
  const track=(name,params={})=>window.AURATracking?.event(name,{...promotion,...params});
  offer.querySelector('.preorder-offer__eyebrow').textContent="COASTGO + YOGA CRUISER · THROUGH 21 OCTOBER";
  offer.querySelector('#preorderOfferTitle').innerHTML='Two boards.<br><span>FREE SHIPPING*</span>';
  offer.querySelector('.preorder-offer__price').textContent='CoastGo AUD $299 · Yoga Cruiser AUD $749';
  offer.querySelector('.preorder-offer__value').textContent='One code. More time on the water.';
  const copyButton=offer.querySelector('[data-promo-code-copy]');
  copyButton.hidden=false;copyButton.style.display='';
  copyButton.innerHTML='<strong>AURAFREESHIP</strong><span>Copy code</span>';
  copyButton.setAttribute('aria-label','Copy promo code AURAFREESHIP');
  offer.querySelector('.preorder-offer__copy').textContent='Automatically applied in the cart. CoastGo: eligible standard regions only; express extra, remote quote. Yoga Cruiser: Gold Coast / Brisbane Metro and QLD / NSW / ACT major cities, coastal areas & Melbourne Metro. Ends 21 October 2026, Queensland time. Select your region to confirm.';
  const coastLink=offer.querySelector('[data-preorder-offer-shop]');
  coastLink.href='products/coast-go.html';coastLink.textContent='Shop CoastGo';
  const yogaLink=document.createElement('a');yogaLink.className='btn btn-primary';yogaLink.href='products/yoga-cruiser.html?colour=glacier';yogaLink.textContent='Shop Yoga Cruiser';coastLink.after(yogaLink);
  const visual=offer.querySelector('.preorder-offer__visual');
  const yogaImage=document.createElement('img');yogaImage.src='assets/products/yoga-cruiser/glacier-blue/AP734955_yoga-cruiser_11ft_glacier-blue_amazon-01-main-package.jpg';yogaImage.alt='Yoga Cruiser Glacier Blue';
  visual.append(yogaImage);visual.style.gridTemplateColumns='1fr 1fr';visual.style.gap='8px';
  const seen=()=>{try{return sessionStorage.getItem(storageKey)==='seen'}catch{return false}};
  const open=(source,manual=false)=>{if(!policy.freeShippingActive()){if(offer.open)offer.close();return;}if(offer.open||document.querySelector('dialog[open]')||(!manual&&seen()))return;offer.showModal();try{sessionStorage.setItem(storageKey,'seen')}catch{}track('view_promotion',{promotion_source:source});};
  document.querySelectorAll('[data-preorder-offer-open]').forEach(button=>button.addEventListener('click',()=>open('manual',true)));
  const dismiss=method=>{if(offer.open){offer.close();track('dismiss_promotion',{dismiss_method:method})}};
  offer.querySelectorAll('[data-preorder-offer-close]').forEach(button=>button.addEventListener('click',()=>dismiss('button')));
  coastLink.addEventListener('click',()=>track('select_promotion',{selected_product:'coast-go'}));
  yogaLink.addEventListener('click',()=>track('select_promotion',{selected_product:'yoga-cruiser'}));
  copyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(policy.shippingCode);copyButton.querySelector('span').textContent='Copied';setTimeout(()=>copyButton.querySelector('span').textContent='Copy code',1800);track('copy_promotion_code')}catch{copyButton.querySelector('span').textContent='AURAFREESHIP'}});
  offer.addEventListener('click',event=>{if(event.target===offer)dismiss('backdrop')});
  offer.addEventListener('cancel',event=>{event.preventDefault();dismiss('escape')});
  window.addEventListener('pageshow',()=>open('return_visit'));
  window.addEventListener('aura:coastgo-change',()=>open('promotion_transition'));
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)open('return_visit')});
  if(policy.freeShippingActive())setTimeout(()=>open('automatic'),850);
})();
