(()=>{
const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let data,requestId=crypto.randomUUID();
const date=value=>new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Brisbane',dateStyle:'medium',timeStyle:'short'}).format(new Date(value*1000));
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error)}
async function api(body){const token=sessionStorage.getItem('aura_admin_token')||$('token').value.trim();const response=await fetch('/api/admin/inventory',{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},cache:'no-store',...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||`HTTP ${response.status}`);sessionStorage.setItem('aura_admin_token',token);return result;}
function rows(){const search=$('search').value.toLowerCase();$('rows').innerHTML=data.products.filter(p=>(!$('nonzero').checked||p.total||p.tracked)&&`${p.sku} ${p.name}`.toLowerCase().includes(search)).map(p=>`<tr><td>${esc(p.name)}<small>${esc(p.sku)} · ${p.tracked?`Online: ${p.saleLocations.map(l=>esc(data.locations[l])).join(', ')}`:'Untracked / pre-order'}</small></td>${Object.keys(data.locations).map(l=>`<td>${p.balances[l]}</td>`).join('')}<td>${p.total}</td><td>${Object.values(p.reserved).reduce((a,b)=>a+b,0)}</td><td class="${p.tracked&&p.available<=p.reorder?'low':''}">${p.tracked?p.available:'—'}</td><td>${p.landedCostUSD===null?'Unknown':p.landedCostUSD.toFixed(2)}</td></tr>`).join('')}
function render(){ $('auth').hidden=true;$('content').hidden=false;$('initialize').hidden=data.initialized;for(const id of ['stock','operations','history-panel'])$(id).hidden=!data.initialized;if(!data.initialized){status('Not initialized. No stock has been changed.');return}
 const sums=Object.fromEntries(Object.keys(data.locations).map(l=>[l,data.products.reduce((n,p)=>n+p.balances[l],0)]));$('stats').innerHTML=[['GC on hand',sums.gc],['Factory on hand',sums.factory],['Transit → GC',sums.gc_transit],['Transit → Amazon',sums.amazon_transit],['All locations',Object.values(sums).reduce((a,b)=>a+b,0)]].map(([title,n])=>`<div class="stat">${title}<strong>${n}</strong></div>`).join('');
 $('source').textContent=`Opening snapshot: ${data.sourceAsOf||date(data.initializedAt)}. This backend is now the operational ledger; the original Sheet is not automatically overwritten.`;
 $('exceptions').textContent=data.exceptions.map(e=>`${e.orderNumber}: ${e.error}`).join('\n');$('sku').innerHTML=data.products.map(p=>`<option value="${esc(p.sku)}">${esc(p.sku)} · ${esc(p.name)}</option>`).join('');for(const id of ['from','to'])$(id).innerHTML='<option value="">Outside inventory / —</option>'+Object.entries(data.locations).map(([key,label])=>`<option value="${key}">${esc(label)}</option>`).join('');$('from').value='gc_transit';$('to').value='gc';rows();
 $('history').innerHTML=data.movements.slice(0,500).map(m=>`<tr><td>${date(m.createdAt)}</td><td>${esc(m.type)}</td><td>${esc(m.sku)}</td><td>${m.quantity}</td><td>${esc(data.locations[m.from]||'—')} → ${esc(data.locations[m.to]||'—')}</td><td>${esc(m.reference)}<small>${esc(m.note)}</small></td></tr>`).join('');$('source-history').textContent=JSON.stringify(data.sourceHistory,null,2);status(`Loaded ${data.products.length} products · ${data.movements.length} movements. Last ${Math.min(500,data.movements.length)} shown.`);
}
async function refresh(){try{status('Loading…');data=await api();render()}catch(e){status(e.message,true)}}
$('login').onclick=refresh;$('refresh').onclick=refresh;$('search').oninput=rows;$('nonzero').onchange=rows;
$('export').onclick=()=>{if(!data?.initialized)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`aura-inventory-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('import').onclick=async()=>{const file=$('import-file').files[0];if(!file)return status('Select the reviewed JSON file.',true);if(!confirm('Initialize the opening ledger once from this reviewed file?'))return;$('import').disabled=true;try{const body=JSON.parse(await file.text());data=await api({...body,action:'initialize'});render()}catch(e){status(e.message,true)}finally{$('import').disabled=false}};
$('type').onchange=()=>{const type=$('type').value;if(['receipt','return','adjustment_in'].includes(type))$('from').value='';if(['sample','adjustment_out'].includes(type))$('to').value=''};
$('movement').onsubmit=async event=>{event.preventDefault();const body=Object.fromEntries(new FormData(event.target));if(!confirm(`Record ${body.type}: ${body.sku} × ${body.quantity}?`))return;const button=event.target.querySelector('button');button.disabled=true;try{data=await api({...body,action:'movement',requestId});requestId=crypto.randomUUID();event.target.reset();render()}catch(e){status(e.message,true)}finally{button.disabled=false}};
if(sessionStorage.getItem('aura_admin_token'))refresh();
})();
